### ISSUE TITLE
Set CPU_COUNT correctly for Azure

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-ci-setup-feedstock#47] opened 2019-02-12 04:53 UTC
Currently `CPU_COUNT` is set for the previously existing CIs (i.e Travis, Circle, and AppVeyor). However to the best of my knowledge `CPU_COUNT` is likely not set correctly for Azure. Would be good to update the values set in these scripts to configure Azure correctly.

**Comment by isuruf** [comment] 2019-05-08 01:44
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/53 has more discussion, so closing this as a duplicate of #53

**Closed by isuruf** 2019-05-08 01:44 UTC
